### ISSUE TITLE
registrations#create (NoMethodError)

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#250]
```
A NoMethodError occurred in registrations#create:

  undefined method `downcase' for nil:NilClass
  app/models/user.rb:114:in `excluded_login'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.ecosounds.org/my_account
  * HTTP Method: POST
  * IP address : 178.73.192.180
  * Parameters : {"utf8"=>"&#x2713;", "authenticity_token"=>"[CENSORED]", "text"=>"", "user"=>{"email"=>"[CENSORED]@[CENSORED].[CENSORED] ", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Register", "controller"=>"users/registrations", "action"=>"create"}
  * Timestamp  : 2016-02-08 16:19:02 +1000
  * Server : web-01
```

```
-------------------------------
Backtrace:
-------------------------------

  app/models/user.rb:114:in `excluded_login'
  app/controllers/application_controller.rb:487:in `set_then_reset_user_stamper'
```

**Comment by atruskie** [comment]
Looks like this is the faulty line:

https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/user.rb#L114

Because the `user_name` field was blank from the looks of it.

Two things to test/fix:
- ensure client side validation is working for empty `user_name` field
- determine why the `:user_name` validator was not run first (https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/user.rb#L100)

**Comment by atruskie** [comment]
Another NoMethod error on the same endpoint.
These errors currently seem to be generated by spam email addresses.

```
A NoMethodError occurred in registrations#create:

  undefined method `downcase' for nil:NilClass
  app/models/user.rb:114:in `excluded_login'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.ecosounds.org/my_account
  * HTTP Method: POST
  * IP address : 91.200.12.82
  * Parameters : {"utf8"=>"&#x2713;", "authenticity_token"=>"[CENSORED]", "text"=>"", "user"=>{"email"=>"[CENSORED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Register", "controller"=>"users/registrations", "action"=>"create"}
  * Timestamp  : 2016-02-12 06:44:20 +1000
  * Server : web-01
  * Rails root : /home/ubuntu/bioacoustics/www/production/releases/20160206132834Z
  * Process: 14525
```

```
-------------------------------
Backtrace:
-------------------------------

  app/models/user.rb:114:in `excluded_login'
  app/controllers/application_controller.rb:487:in `set_then_reset_user_stamper'

```

**Comment by cofiem** [comment]
I was looking into this, and I've had a thought: This could be evidence of the web server not having a `current_user`. If the user was currently logged in, this could mean that there is an issue with more than one web server. The [current user](https://github.com/QutBioacoustics/baw-server/blob/develop/app/controllers/application_controller.rb#L486) being [stored in a thread](https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/user.rb#L205) was mentioned as being a potential issue.

Warning: if this is the case, this could mean that models are being stamped by the wrong (or even no) user for `creator_id`, `updater_id`, or `deleter_id`! See https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/user_change.rb

This needs further investigation.

**Comment by atruskie** [comment]
Fair enough. Next test would be to see if either of the above requests can repro'd in a test environment.

I'll quickly peruse through prod tomorrow to see if anything obvious is out of place.

**Comment by atruskie** [comment]
However, I checked both email addresses sent in the requests above (before censoring) and they were on spam lists

**Comment by cofiem** [comment]
I'm not sure about the next step for this issue.

**Comment by atruskie** [comment]
As far as I can see there has been no loadbalancer issues.

Next steps would be to add tests with the same parameters as those requests to see if the same state can be reached. If not we go down the user_stamper investigation path.

**Comment by atruskie** [comment]
This error just happened again:

```
A NoMethodError occurred in registrations#create:

undefined method `downcase' for nil:NilClass
app/models/user.rb:114:in `excluded_login'
------------------------------- Request:

* URL        : https://ecosounds.org/my_account
* HTTP Method: POST
* IP address : [FILTERED]
* Parameters : {"utf8"=>"&#x2713;", "authenticity_token"=>"[FILTERED]", "text"=>"[FILTERED]", "user"=>{"email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Register", "controller"=>"users/registrations", "action"=>"create"}
```
