### ISSUE TITLE
audio_recordings#filter (FloatDomainError) "NaN"

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#251]
Bug report from website mailer:

```
A FloatDomainError occurred in audio_recordings#filter:

  NaN
  lib/modules/api/response.rb:142:in `ceil'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.ecosounds.org/audio_recordings/filter
  * HTTP Method: POST
  * IP address : [CENSORED]
  * Parameters : {"filter"=>{"siteId"=>{"in"=>[1352]}}, "paging"=>{"disablePaging"=>true}, "projection"=>{"include"=>["id", "uuid", "siteId", "durationSeconds", "recordedDate"]}, "sorting"=>{"orderBy"=>"id", "direction"=>"asc"}, "format"=>"json", "controller"=>"audio_recordings", "action"=>"filter", "audio_recording"=>{}}
  * Timestamp  : 2016-02-11 14:19:45 +1000
  * Server : web-01
  * Rails root : [CENSORED]/www/production/releases/20160206132834Z
  * Process: [CENSORED]
```

```
-------------------------------
Backtrace:
-------------------------------

  lib/modules/api/response.rb:142:in `ceil'
  lib/modules/api/response.rb:142:in `build'
  lib/modules/api/controller_helper.rb:123:in `respond_filter'
  app/controllers/audio_recordings_controller.rb:197:in `filter'
  app/controllers/application_controller.rb:487:in `set_then_reset_user_stamper'
```

**Comment by atruskie** [comment]
Just repro'd this error: occurs when there are no audio recordings in a site

**Comment by atruskie** [comment]
:+1:
