### ISSUE TITLE
Add support for higher sample rate recordings (e.g. 96kHz)

### ISSUE THREAD

**Issue by peichins** [QutBioacoustics/baw-server#343]
When playing back high sample rate audio, this error occurs:

```
An ArgumentError occurred in media#show:

sample_rate must be in [8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000]: 96000. Provided parameters: {:uuid=>"a6851f44-1968-4330-9ab2-9edef273fdf3", :format=>"mp3", :media_type=>"audio/mpeg", :start_offset=>4339.0, :end_offset=>4369.0, :channel=>0, :sample_rate=>96000, :datetime_with_offset=>Sun, 06 Aug 2017 22:39:41 AEST +10:00, :original_format=>".wav", :window=>512, :window_function=>"Hamming", :colour=>"g"}
vendor/bundle/ruby/2.3.0/bundler/gems/baw-workers-54f28d351a5b/lib/baw-workers/storage/common.rb:155:in `validate_sample_rate'
------------------------------- Request:

* URL        : https://www.ecosounds.org/audio_recordings/460996/media.mp3?end_offset=4369&start_offset=4339&user_token=NppLN6S2sBEYZXgLfzYs
* HTTP Method: GET

vendor/bundle/ruby/2.3.0/bundler/gems/baw-workers-54f28d351a5b/lib/baw-workers/storage/common.rb:155:in `validate_sample_rate'
vendor/bundle/ruby/2.3.0/bundler/gems/baw-workers-54f28d351a5b/lib/baw-workers/storage/audio_cache.rb:27:in `file_name'
vendor/bundle/ruby/2.3.0/bundler/gems/baw-workers-54f28d351a5b/lib/baw-workers/storage/audio_cache.rb:43:in `file_names'
vendor/bundle/ruby/2.3.0/bundler/gems/baw-workers-54f28d351a5b/lib/baw-workers/storage/common.rb:64:in `path_info'
app/controllers/media_controller.rb:162:in `media_response'
app/controllers/media_controller.rb:111:in `supported_media_response'
app/controllers/media_controller.rb:52:in `show'
```

The data is valid, and we should support media requests at that sample rate

**Comment by atruskie** [comment]
This issue was moved to QutBioacoustics/baw-workers#61
